# Generated by Django 4.2.7 on 2026-05-29 21:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_fix_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant total de la facture', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='worker',
            field=models.ForeignKey(help_text='Utilisateur qui a créé la facture', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='worker',
            field=models.ForeignKey(help_text='Utilisateur qui a enregistré la vente', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
