# Generated by Django 4.2.7 on 2026-05-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_total_amount_alter_invoice_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total de la facture (calculé après ajout des ventes)', max_digits=10),
        ),
    ]
